name: Go tests
on:
  push:
  pull_request:
  workflow_disptach:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Get dependencies
        run: |
          go get -v -t ./...
      - name: Build and Test
        run: |
          go build -v ./...
          go test -v ./...